name: Test

permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  setupEnvironment:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
  
  runTests:
    name: Run Tests
    needs: setupEnvironment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Generate parser and test it
        shell: bash
        run: |
          npm install
          npm run build
          npm test